# Çoklu Doğrusal Regresyon

## Model

In [6]:
import pandas as pd
import numpy as np
import seaborn as sns
import statsmodels.api as sm
df = pd.read_csv("./Advertising.csv")
df = df.iloc[:,1:len(df)]# index problemini gidermek için
df.head()
X = df.drop('sales',axis=1)
y = df[["sales"]]

In [3]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [4]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

#### Statsmodels ile model kurmak

In [8]:
lm = sm.OLS(y,X)

In [11]:
model = lm.fit()

In [12]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Thu, 24 Dec 2020   Prob (F-statistic):                   2.43e-171
Time:                        15:04:47   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

* R-squared: Bağımsız değişkenlerin bağımlı değişkeni açıklama yüzdesidir. ( Bu modelde 0.98 )
* Adj. R-squared: R2 değeri değişken eklendikçe şişme eğilimindedir. Her yeni değişken eklendiğinde her R2 artması yanıltıcı olabilir. Formülasyonuyla alakalıdır.
* F-statistic: Anlamlılığını test etmek için kullanılır.  * Prob(F-statistic): 0.05'ten oldukça küçük olduğu için model anlamlıdır denilebilir.                     
* Coef: Bağımsız değişkenlerin katsayısını ifade eder(B1,B2,B3). ***Yani örneğin TV değişkeninin katsayısı = 0.05dir. Diğer değişkenler sabit varsayıldığında ve TV satışlarındaki 1 birim artış bağımlı değişkende 0.05 birim artışa sebep olacaktır anlamında gelir.***
* std error: Katsayıların standart hatası            
* P>|t|: 0.05'ten büyük olduğu için değişkenlerin anlamlı olduğunu ifade eder.

#### Scikit ile Model Kurma

In [14]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()

In [15]:
model = lm.fit(X, y)

In [16]:
model.intercept_

array([2.93888937])

In [17]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

   _Sales = 2.94 + 0.04*TV + 0.19*Radio - 0.001*Newspaper_

### Tahmin

30 Birim TV, 10 Birim Radio, 40 Birim Gazete

In [34]:
sales = 2.94 + 0.04*30 + 0.19*10 - 0.001*40
sales

5.999999999999999

In [36]:
new_ = [[30],[10],[40]]

new_ = pd.DataFrame(new_).T  #Transpozu alındı
                             #satır->sütun, sütun->satır

new_

0   1   2
0  30  10  40

In [32]:
model.predict(new_)

array([[6.15562918]])

In [37]:
from sklearn.metrics import mean_squared_error

In [38]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [44]:
predicted = model.predict(X)

In [45]:
MSE = mean_squared_error(y, predicted)
MSE

2.784126314510936

In [46]:
import numpy as np
rmse = np.sqrt(MSE)
rmse

1.6685701407225697

### Model Tuning (Model Doğrulama)

In [47]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [48]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

### Holdout

In [94]:
from sklearn.model_selection import train_test_split

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.20, random_state=99)

1) X bağımsız değişkenleri ve y bağımlı değişkeni test ve train veri seti olarak ikiye ayrıldılar(X_train,y_train & X_test,y_test).                                    
2) Test veri setinin büyüklüğü %20 olarak ayarlandı.     
3) Random_state = 99 yapılarak her seferinde farklı veriler gelmesi engellendi.

In [52]:
X_train.head()

TV  radio  newspaper
16    67.8   36.6      114.0
51   100.4    9.6        3.6
97   184.9   21.0       22.0
164  117.2   14.7        5.4
71   109.8   14.3       31.7

In [78]:
lm = LinearRegression() # Linear model oluşturuldu.
model = lm.fit(X_train,y_train) # linear model train veri seti üzerine fit edildi.
model_rmse = np.sqrt((mean_squared_error(y_train, model.predict(X_train))))
#Modelde X_train verileri kullanılarak y_train tahmin edilecek ve gerçek y_train ile karşılaştırılacak
print("Eğitim Hatası:",model_rmse)

Eğitim Hatası: 1.7236824822650751


In [76]:
model_rmse = np.sqrt(mean_squared_error(y_test,model.predict(X_test)))
print("Test hatası: ",model_rmse)

Test hatası:  1.4312783138301641


Eğer test ve train seti ayrılırken random_state = 1 yapılırsa yani rastgelelik oluşursa sonuçları yanıltıcı olarak değerlendirilebilir. Bu yanılmayı engellemek için K-Fold CV kullanılır.

### K-Fold Cross Validation

In [80]:
from sklearn.model_selection import cross_val_score

In [93]:
cvs = cross_val_score(model, X_train,y_train, cv = 10, scoring="neg_mean_squared_error")
cvs

array([-2.1019073 , -2.48953197, -3.09704214, -2.34694216, -3.68175761,
       -1.8691401 , -3.18173007, -4.1927349 , -2.17128376, -8.03821974])

Train seti üzerinden 10 farklı hata hesaplandı. Yani train seti 10 parçaya bölündü 1 parça dışarıda bırakılarak 9 parça ile train yapıldı ve kalan 1 parça ile test edildi. Ve bu her parça test edilene kadar uygulandı.

In [90]:
cvs_mean = np.mean(-cvs)
cvs_mean

3.317028974234127

In [91]:
# cvs rmse
cvs_rmse = np.sqrt(cvs_mean)
cvs_rmse

1.821271252239525