# **_NumPy(Numerical Python) nedir?_**
          
* Bilimsel hesaplamalar için kullanılır.  
* Arrayler / çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar.  
* Listelere benzerdir, farkı; verimli veri saklama ve vektörel operasyonlardır.  -Veri tipi önemli değildir Fix Type a zorlar ve her değişken için tek bilgi tutar.

## **_Neden NumPy?_**

In [4]:
a=[1,2,3,4]
b=[2,3,4,5]

In [5]:
ab = []

for i in range(0,len(a)):
    ab.append(a[i]*b[i])
    
ab

[2, 6, 12, 20]

In [6]:
import numpy as np

In [7]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])


In [8]:
a*b

array([ 2,  6, 12, 20])

* Daha karmaşık işlemleri daha kolay şekilde yapmaya yarar.    
* Örneğin 4. hücredeki a ve b listelerinin her bir elemanını ayrı bir değişken olarak görürken 7. hücredeki a ve b np.array lerinin elemanlarını tek bir np.array değişkeni olarak görür. böylece 4 kat daha az memory harcanır.

## _**NumPy Array'i Oluşturmak**_

In [9]:
import numpy as np

In [10]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [11]:
a = np.array([1,2,3,4,5])

In [12]:
type(a)

numpy.ndarray

In [18]:
b = np.array(["a",2,4.5])

In [19]:
type(b)

numpy.ndarray

In [20]:
b

array(['a', '2', '4.5'], dtype='<U3')

* Görüldüğü üzere numpy içerisindeki değişkenlerden birini seçerek dtype'ı tek bir veriye indirgiyor. tanımlarken float ve int olan 2 ve 4.5 değerleri numpy arrayinde str olarak saklanıyor.

* array'in değişken tipini array'i tanımlarken belirlemek için **_dtype =_** parametresi kullanılır.

In [22]:
c = np.array([2.4,"a",3,5.3134], dtype="str")

In [24]:
c

array(['2.4', 'a', '3', '5.3134'], dtype='<U6')

In [25]:
d = np.array([2.4,"a",3,5.3134], dtype="int")

ValueError: invalid literal for int() with base 10: 'a'

* **-str to int yapamaz.**

In [26]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.full((3,5),5,dtype="int")

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [29]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [30]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [31]:
np.random.normal(10,4,(3,4))

array([[11.11264028, 14.12510554, 13.51933822,  3.33872713],
       [ 2.87774063,  6.32147261,  9.03563156,  3.74841463],
       [ 4.34651773, 14.27002056,  8.88719091,  4.52766561]])

In [32]:
np.random.randint(0,10,(3,3))

array([[8, 5, 5],
       [3, 4, 4],
       [9, 8, 6]])

* zeros ile 0'lar vektörü    
* ones ile 3x5 lik 2 boyutlu 1'ler matrisi     
* full ile 3x5 lik 2 boyutlu istediğimiz sayıdan oluşan matris oluşturabiliriz.

* **-arange ile istediğimiz aralıkta ve istediğimiz oranda artan vektör oluşturabiliriz.**

* linspace ile 0 ile 1 arasında 10 adet sayı içeren vektör oluşturabiliriz.      
* **-random.normal ile normal dağılıma sahip ortalaması 10 standart sapmasını 4 verecek şekilde 3x4 lük matris oluşturabiliriz.                        
* random.randint ile 0 ile 10 arasında 3x3 lük rastgele matris oluşturabiliriz.**

## _**NumPy Array Özellikleri**_

* **ndim:** _boyut sayısı_
* **shape:** _boyut bilgisi_
* **size:** _toplam eleman sayısı_
* **dtype:** _array tipi_

In [34]:
np.random.randint(10,size=10)

array([9, 0, 7, 0, 8, 2, 5, 6, 5, 4])

In [36]:
a = np.random.randint(10,size=10)

In [37]:
a.ndim

1

In [38]:
a.shape

(10,)

In [39]:
a.size

10

In [40]:
a.dtype

dtype('int32')

### **_Yeniden Şekillendirme(Reshaping)_**

In [41]:
import numpy as np

In [96]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
a = np.arange(1,10)

In [45]:
a.ndim

1

In [47]:
b = a.reshape((1,9))

In [48]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [49]:
b.ndim

2

### **_Array Birleştirme(Concatenation)_**

In [50]:
import numpy as np

In [51]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [53]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [54]:
z = np.array([7,8,9])

In [55]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
# iki boyut

In [57]:
a = np.array([[1,2,3],
              [4,5,6]])

In [95]:
np.concatenate([a,a])

array([1, 2, 3, 1, 2, 3])

In [59]:
np.concatenate([a,a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [60]:
 # axis = 0 satırı axis = 1 sütun bazlı birleştirmeyi ifade eder

### **_Array Ayırma(Splitting)_**

In [61]:
import numpy as np

In [62]:
x = np.array([1,2,3,99,99,3,2,1])

In [63]:
np.split(x, [3,5])    

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [64]:
a,b,c = np.split(x, [3,5])

In [65]:
a

array([1, 2, 3])

In [66]:
b

array([99, 99])

In [67]:
c

array([3, 2, 1])

In [68]:
#iki boyutlu ayırma

In [70]:
m = np.arange(16).reshape(4,4)

In [71]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [72]:
ust, alt = np.vsplit(m,[2])

In [73]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [74]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [108]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [76]:
sag, sol = np.hsplit(m,[2])

In [77]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [78]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

### **_Sıralama(Sorting)_**

In [80]:
import numpy as np

In [81]:
v = np.array([2,3,5,1,7,0])

In [87]:
np.sort(v) 

#numpy ın içinden sort methodu çağrılırsa array in orjinalini değiştirmez

array([0, 1, 2, 3, 5, 7])

In [83]:
v

array([2, 3, 5, 1, 7, 0])

In [84]:
v.sort()

In [85]:
v

array([0, 1, 2, 3, 5, 7])

In [88]:
#iki boyutlu array sıralama

In [90]:
k = np.random.normal(20,5,(3,3))

In [91]:
k

array([[21.8002009 , 21.93245395, 30.24522948],
       [18.40622927, 26.327005  , 19.85269588],
       [22.55123156, 24.16274557, 19.870601  ]])

In [94]:
np.sort(k,axis=1)

array([[21.8002009 , 21.93245395, 30.24522948],
       [18.40622927, 19.85269588, 26.327005  ],
       [19.870601  , 22.55123156, 24.16274557]])

In [93]:
np.sort(k,axis=0)

array([[18.40622927, 21.93245395, 19.85269588],
       [21.8002009 , 24.16274557, 19.870601  ],
       [22.55123156, 26.327005  , 30.24522948]])

### **_Index ile Elemanlara Erişmek_**

In [97]:
#iki boyutlu arrayin elemanına index ile erişmek

In [125]:
j = np.random.randint(10, size = (3,5))
j

array([[6, 5, 5, 8, 2],
       [6, 1, 1, 1, 1],
       [8, 3, 1, 0, 8]])

In [102]:
j[0,0]   #önce satır sonra sütun

5

In [101]:
j[1,1]

9

In [103]:
j[1,1] = 22

In [104]:
j[1,1]

22

In [107]:
j[1,4] = 5.1    

# var olan bir arraye farklı tip ekleme yapılırsa arrayin tipini göre ekledi

In [106]:
j

array([[ 5,  8,  0,  9,  2],
       [ 7, 22,  2,  4,  5],
       [ 9,  7,  4,  9,  1]])

### **_Alt Küme İşlemleri(Slicing)_**

In [109]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [111]:
a[0:3]      #ilk değer dahil ikinci değer dahil değil 'e kadar'

array([20, 21, 22])

In [112]:
a[:3]

array([20, 21, 22])

In [113]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [114]:
a[1::2]

array([21, 23, 25, 27, 29])

In [115]:
a[::2]

array([20, 22, 24, 26, 28])

In [116]:
# iki boyutlu slicing

In [120]:
m = np.random.randint(10, size=(5,5))

In [122]:
m[:,0]    # virgülden önce satır virgülden sonra sütun işlemleri yapılır

array([6, 5, 3, 1, 3])

In [123]:
m[1,:]

array([5, 0, 2, 0, 0])

In [124]:
m[0:2:2,0:3]

array([[6, 4, 4]])

### **_Alt Küme Üzerinde İşlem Yapmak_**

In [134]:
j = np.random.randint(10, size = (5,5))
j

array([[2, 5, 6, 8, 2],
       [3, 0, 2, 2, 6],
       [2, 1, 4, 6, 0],
       [5, 3, 9, 6, 6],
       [7, 0, 4, 8, 7]])

In [127]:
alt_j = j[0:3,0:2]
alt_j

array([[9, 6],
       [0, 1],
       [1, 4]])

In [131]:
alt_j[0,0] = 9999

In [129]:
alt_j[1,1] = 8888

In [132]:
alt_j

array([[9999,    6],
       [   0, 8888],
       [   1,    4]])

In [133]:
j

array([[9999,    6,    1,    6,    0],
       [   0, 8888,    7,    7,    9],
       [   1,    4,    9,    8,    6],
       [   2,    3,    4,    2,    8],
       [   4,    3,    6,    1,    0]])

In [135]:
k = np.random.randint(10, size = (5,5))
k

array([[3, 5, 6, 5, 2],
       [2, 1, 6, 9, 7],
       [0, 4, 1, 7, 1],
       [8, 0, 2, 8, 9],
       [1, 0, 7, 7, 8]])

In [142]:
alt_k = k[0:3,0:2].copy()     
#.copy metoduyla alt kümeyi bağımsızlaştırır ve 
#değişikliklerden ana küme etkilenmez.

In [137]:
alt_k

array([[3, 5],
       [2, 1],
       [0, 4]])

In [139]:
alt_k[1,1] = 9999

In [140]:
alt_k

array([[   3,    5],
       [   2, 9999],
       [   0,    4]])

In [141]:
k

array([[3, 5, 6, 5, 2],
       [2, 1, 6, 9, 7],
       [0, 4, 1, 7, 1],
       [8, 0, 2, 8, 9],
       [1, 0, 7, 7, 8]])

### **_Fancy Index ile Elemanlara Erişmek_**

In [165]:
import numpy as np
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [144]:
v[1]

3

In [145]:
v[3]

9

In [146]:
[v[1],v[3]]

[3, 9]

In [150]:
al_getir = [1,3]

In [151]:
v[al_getir]

array([3, 9])

In [152]:
# İki boyutta Fancy

In [154]:
m = np.arange(9).reshape(3,3)

In [155]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [156]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [157]:
m[satir,sutun]

array([1, 5])

In [158]:
# basit index ile fancy index

In [159]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [160]:
m[0,[1,2]]

array([1, 2])

In [163]:
#slice ile fancy

In [162]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

### **_Koşullu Eleman İşlemleri_**

In [174]:
import numpy as np
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [168]:
v > 5 # v'nin içindeki değerleirn 5 ten büyük olup olmadığını kontrol eder

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [171]:
v[v<3]

array([0])

In [172]:
v[v>3]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

### **_Matematiksel İşlemler_**

In [176]:
import numpy as np
v = np.arange(1,6,1)
v

array([1, 2, 3, 4, 5])

In [177]:
#ufunc

In [178]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\Emre Uslu\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\emre uslu\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x 

**5 * x0 + x1 =12**                               
**x0 + 3 * x1 = 10**

In [180]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [181]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])